# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            leportella
tagline:          a little bit about me
description:      >
    This a blog from an oceanographer who became passionare about programming.
    I'm a dev, in love with data science that loves to write technical posts 
    about what I'm learning, specially Python, Django and Data Science stuff

url:              "https://leportella.com" # no https
baseurl:          "" # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Leticia Portella'
  url:            https://twitter.com/leleportella

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about.html'}
  - {name: 'Community Work', link: '/community.html'}
  - {name: 'Curriculum', link: '/curriculum.html'}
  - {name: 'Feed', link: '/feed.xml'}

hero_img: posts/ocean.jpg
github:
  repo:             https://github.com/leportella/

google_analytics:   UA-106178084-1 

disqus:
  shortname:  leportella-com

twitter_username: leleportella
github_username: leportella



# SEO PLUGIN
social:
  name: leportella
  links:
    - https://twitter.com/leleportella
    - https://www.linkedin.com/in/leportella
    - https://github.com/leportella

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
#permalink: /:title/

compress_html:
clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
